### ISSUE TITLE
Logging exception info is not JSON serializable

### ISSUE THREAD

**Issue by ehlertjd** [flywheel-io/flywheel-common#4]
Using `log.exception` in an exception handler block results in a new exception being thrown.
Offending line: https://github.com/flywheel-io/python-logging/blob/gevent/flylogging/json_formatter.py#L21

**Comment by ryandavisflywheel** [comment]
Is this the fix https://github.com/flywheel-io/flywheel-common/pull/22#discussion_r286660309 ?

**Comment by ehlertjd** [comment]
Unrelated AFAICT. I believe that this issue has long been fixed.
